version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - VITE_GRAPHQL_HTTP=http://backend:4000
    depends_on:
      - backend
    restart: unless-stopped


