services:
  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_GRAPHQL_HTTP: http://localhost:4000
    environment:
      - NODE_ENV=production
      - VITE_GRAPHQL_HTTP=http://localhost:4000
    depends_on:
      - backend
    ports:
      - "4001:4001"
    restart: unless-stopped


